name: Smart XAPK Patcher (SSL Bypass)

on:
  workflow_dispatch:

jobs:
  xapk-patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip wget curl git apktool zipalign zip
        pip install reflutter frida-tools pyghidra capstone pyelftools
        
        # Download Uber APK Signer
        mkdir -p tools
        LATEST_SIGNER_URL=$(curl -s https://api.github.com/repos/patrickfav/uber-apk-signer/releases/latest | grep "browser_download_url.*\.jar" | cut -d '"' -f 4)
        wget -O tools/uber-apk-signer.jar "$LATEST_SIGNER_URL"

    - name: Patch XAPK
      run: |
        mkdir -p output_app
        INPUT_XAPK=$(find input_app/ -name "*.xapk" -o -name "*.apks" -o -name "*.zip" | head -n 1)
        
        if [ -z "$INPUT_XAPK" ]; then
          echo "[-] Error: No XAPK/APKS found in input_app/"
          exit 1
        fi
        
        echo "[+] Processing XAPK: $INPUT_XAPK"
        python3 tools/xapk_patcher.py "$INPUT_XAPK" "output_app/patched_app.xapk"

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: Patched-XAPK-Ready
        path: output_app/*.xapk
